title: The Cold Fish
description: It's genetic, cultural, and acceptable.  The warmth you are not feeling is practiced.
show_downloads: false
google_analytics:
theme: jekyll-theme-slate
twitter_username: jasonemiller
github_username: millerj870